### ISSUE TITLE
How use the lib by create-react-app??

### ISSUE THREAD

**Issue by leermao** [alewin/useWorker#104]
![image](https://user-images.githubusercontent.com/11629887/111064187-95300580-84ed-11eb-964d-0b4cd22d1009.png)

**Comment by nassif7** [comment]
it seems the latest version is not working ad this might be a bug! 
try to install the previous version, it worked for me.

**Comment by alewin** [comment]
there's a problem with the latest version, thanks for the report! As soon as we release the fix I'll warn you in this issue

**Comment by leermao** [comment]
thank you

**Comment by zant** [comment]
Closing as I just tested it with the latest version.

Please let us know if this is still an issue
