### ISSUE TITLE
Update to react 17

### ISSUE THREAD

**Issue by MatanYemini** [alewin/useWorker#117]
I don't think that description is needed.

I don't mind to do, just update me if you allow.

Thanks.

**Comment by cgarrovillo** [comment]
What do you think needs updating? AFAIK this is still compatible with React 17.

**Comment by cassm** [comment]
I believe I've run into the same issue here. As suggested in the error message, it does work fine with --legacy-peer-deps, so it's not critical.

Steps to reproduce: run `npm install --save @koale/useworker` in a project which uses React 17.0.2
Expected result: package installs
Actual result: receive the following error:
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-client@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @koale/useworker@4.0.2
npm ERR! node_modules/@koale/useworker
npm ERR!   @koale/useworker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/cassm/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cassm/.npm/_logs/2022-03-09T12_41_04_040Z-debug-0.log

The mentioned log files are attached.
[eresolve-report.txt](https://github.com/alewin/useWorker/files/8214765/eresolve-report.txt)
[2022-03-09T12_41_04_040Z-debug-0.log](https://github.com/alewin/useWorker/files/8214769/2022-03-09T12_41_04_040Z-debug-0.log)

**Comment by VittorioAccomazzi** [comment]
Same issue with react 18:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-typescript-web-wrk-canvas@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @koale/useworker@4.0.2
npm ERR! node_modules/@koale/useworker
npm ERR!   @koale/useworker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/vittorio/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vittorio/.npm/_logs/2022-04-09T14_41_58_833Z-debug-0.log

```
however using `--legacy-peer-deps` seems to workaround the problem

**Comment by jonbeacherdomuso** [comment]
I have the same issue and I cant fix with --legacy-peer-deps

**Comment by alewin** [comment]
I will fix this in the next release, thanks!

**Comment by atrakh** [comment]
Any timeline on the next release?

**Comment by yezzer** [comment]
Any update on this @alewin ? :)

**Comment by Mariam-maghraby** [comment]
When will be the next release @alewin?  :) 

> I will fix this in the next release, thanks!

**Comment by naorpeled** [comment]
We're planning on releasing a fix for it soon™️

For anyone seeing this thread and wanting a temporary fix you can add the following to your `package.json`

```json
 .....
  "overrides": {
    "@koale/useworker": {
      "react": "^17.0.0"
    }
  }
 ....
```
