### ISSUE TITLE
Compatability Issue with react@17.0.2

### ISSUE THREAD

**Issue by reese1515** [alewin/useWorker#123]
I'm using react ^17.0.2 and when I attempted to do the install i'm getting the following error 
$ npm install --save @koale/useworker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client-app@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project   
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @koale/useworker@4.0.2
npm ERR! node_modules/@koale/useworker
npm ERR!   @koale/useworker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Is this meant to work with react version 17+ or would I need to go back to version 16?

**Comment by empawlo** [comment]
Ran into the same error, please help. In addition, it would be ideal to also support React 18.

**Comment by nrgapple** [comment]
Any update on compatibility with new react versions?

**Comment by alewin** [comment]
I will fix this in the next release, thanks

**Comment by tmaihoff** [comment]
@alewin do you have an estimate ? Getting the same ERR with  `"react": "18.2.0",`

**Comment by agboola-osho** [comment]
Me too

**Comment by agboola-osho** [comment]
> I will fix this in the next release, thanks

Is it now fixed
