### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by agboola-osho** [alewin/useWorker#131]
When I try to install the package I get this error:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @koale/useworker@4.0.2
npm ERR! node_modules/@koale/useworker
npm ERR!   dev @koale/useworker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\obaag\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\obaag\AppData\Local\npm-cache\_logs\2023-03-15T13_08_14_208Z-debug-0.log

please resolve ASAP

**Comment by monski** [comment]
try forcing it `npm install --save @koale/useworker --force`
