### ISSUE TITLE
react@18 compatibility

### ISSUE THREAD

**Issue by architeq** [alewin/useWorker#134]
for projects that use web expo with the expo-camera component, it will generate an error that prevents the use of camera. attached thread.     
https://github.com/expo/expo/issues/17846

**Comment by sunnyrod** [comment]
Is there a plan to upgrade peerDependency on react to react@18?
https://github.com/alewin/useWorker/blob/19d2f2461e558e9d8174fe9afc11cabc4a736999/pnpm-lock.yaml#L15

**Comment by huelmoandres** [comment]
Hi, we need you to update the library to React 17 or React 18.

**Comment by croche2574** [comment]
same here

**Comment by codercoin98** [comment]
same

**Comment by jpwallace22** [comment]
@croche2574 @codercoin98 Sadly, I don't think this is being maintained any longer. I reached out to take it over but never got a response. I have a very simular package [here](https://github.com/jpwallace22/use-react-workers) that has the same functionality with some extra hooks as well. This is also being actively maintained. 

Happy hacking!

**Comment by dhwang** [comment]
maybe @alewin is no more

**Comment by rafark** [comment]
> @croche2574 @codercoin98 Sadly, I don't think this is being maintained any longer. I reached out to take it over but never got a response. I have a very simular package [here](https://github.com/jpwallace22/use-react-workers) that has the same functionality with some extra hooks as well. This is also being actively maintained.
> 
> Happy hacking!

I want to try your library. Is it library a fork of this one?

**Comment by jpwallace22** [comment]
> I want to try your library. Is it library a fork of this one?
It is a little more than a fork. It updates it and adds a decent amount more.

**Comment by naorpeled** [comment]
We're planning on releasing a fix for it soon™️

For anyone seeing this thread and wanting a temporary fix you can add the following to your `package.json`

```json
 .....
  "overrides": {
    "@koale/useworker": {
      "react": "^18.0.0"
    }
  }
 ....
```
