### ISSUE TITLE
Consider a TypeScript support

### ISSUE THREAD

**Issue by Pigotz** [alewin/useWorker#18]
It would be nice to have a **TypeScript** support in order to reach a larger number of code bases

**Comment by alewin** [comment]
I added the typescript support using a simple `index.d.ts` types definition:

```typescript
export type HookOptions = {
  timeout?: number;
  dependencies?: Array<String>;
}
export type HookReturnType = [(...fnArgs: any[]) => (Promise<any>), string, () => void];
export function useWorker(fn: any, options: HookOptions): HookReturnType;
```

Could you give me some feedback @Pigotz ?
I've done some tests with a typescript project and everything is working correctly ;)

Pull Request: https://github.com/alewin/useWorker/pull/19
