### ISSUE TITLE
[Proposal] migrate library to TypeScript

### ISSUE THREAD

**Issue by IljaDaderko** [alewin/useWorker#26]
Would you consider migrating this library to typescript to ensure better type safety and prevent some bugs from future contributors? I've started using this hook and am in ❤️with how simple it is.

In order to do this following "Todos" are probably required:

- [x] Re-write source in TypeScript
- [ ] Configure something like [rollup](https://rollupjs.org/guide/en) to build js files for non typescript users
- [x] Find a way to serve ts files to TypeScript users and built js files to other users
- [ ] Configure CI to build js files for releases

I can start helping out with `Re-write source in TypeScript` if you agree to proceed 👍

**Comment by alewin** [comment]
It would be great @IljaDaderko!!, and very useful, I totally agree 💯 

In these days, I was started to write some tests in [Jest](https://jestjs.io/).
Honestly I started studying typescript recently but I'll try to do my best!

**Comment by IljaDaderko** [comment]
Sweet, I'll start contributing bits and peaces latter this week / weekend 👍

**Comment by IljaDaderko** [comment]
I think this can be closed by #27? Remaining checklist items might not be needed, as it looks they are handled by microbundle? cc @z4o4z

**Comment by alewin** [comment]
yes, we could close this 👍
