### ISSUE TITLE
Question: Are Transferables supported as input or return values from worker?

### ISSUE THREAD

**Issue by jimvermillion** [alewin/useWorker#46]
Hi, I was wondering if [Transferables](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_transferable_objects) were supported in this api.

My use case is passing in some data to a worker and passing back a TypedArray or set of TypedArrays back to the react component.

Thank you for your time!

**Comment by alewin** [comment]
Hi @jimvermillion, it should work

this is the list of supported types: 
|Object type|Notes|
|--- |--- |
|All primitive types|However, not symbols.|
|Boolean objects||
|String objects||
|Date||
|RegExp|lastIndex is not preserved.|
|Blob||
|File||
|FileList||
|ArrayBuffer||
|ArrayBufferView|Including other typed arrays.|
|ImageBitmap||
|ImageData||
|Array||
|Object|Only plain objects (e.g. from object literals)|
|Map||
|Set||

Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)

Let us know if there are any problems with Transferables, so we can close the issue, thanks!

**Comment by alewin** [comment]
Sorry @jimvermillion I read the question very quickly (a misunderstanding).
@gonzachr wrote a very good proposal about this.: https://github.com/alewin/useWorker/issues/47
