### ISSUE TITLE
No OffscreenCanvas compatibility detection

### ISSUE THREAD

**Issue by aofong** [alewin/useWorker#59]
error info
`Unhandled Rejection (ReferenceError): OffscreenCanvas is not defined`

**Comment by alewin** [comment]
@aofong are you using `useWorker 3.2.0` https://github.com/alewin/useWorker/pull/56?

**Comment by aofong** [comment]
> @aofong are you using `useWorker 3.2.0` #56?

yes

**Comment by aofong** [comment]
> @aofong are you using `useWorker 3.2.0` #56?

Used in nwjs, chrome version is 49

**Comment by alewin** [comment]
it looks like NW has some problems with web worker 
https://github.com/nwjs/nw.js/search?q=web+worker&type=Issues

I'll try to do some tests 🤔

**Comment by aofong** [comment]
> it looks like NW has some problems with web worker
> https://github.com/nwjs/nw.js/search?q=web+worker&type=Issues
> 
> I'll try to do some tests 🤔

Thanks, I use useWorker@3.1.0 works fine
