### ISSUE TITLE
Guidance on how to use local dependencies?

### ISSUE THREAD

**Issue by marco-m-alves** [alewin/useWorker#69]
Proposal 3 on https://github.com/alewin/useWorker/issues/36 mentions local dependencies

I would like to use local dependencies to avoid having long functions which are hard to test / debug.

I've tried to use the functionality but I get an `object can not be cloned error`. 

Guidance or an example on how use local dependencies would be helpful. Thank you.

Code below — https://codesandbox.io/s/hopeful-night-l6vw6?file=/src/App.js

```
import React, { useState } from "react";
import "./styles.css";
import { useWorker } from "@koale/useworker";

export default function App() {
  const [message, setMessage] = useState("waiting for go...");
  const [processTextWorker] = useWorker(fnWithLocalDependency, {
    localDependencies: [{ util: util }]
  });
  const handleClick = _ => {
    setMessage("working...");
    processTextWorker("blah", util).then(setMessage);
  };
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <button onClick={handleClick}>go!</button>
      <p>{message}</p>
    </div>
  );
}

const fnWithLocalDependency = text => {
  const a = util.fn1(text);
  const b = util.fn2(text);
  return JSON.stringify({ a, b });
};
const util = {
  fn1: text => `the text is '${text}'`,
  fn2: text => `:${text}:`
};

```

**Comment by marco-m-alves** [comment]
... 
:)

**Comment by gonzachr** [comment]
Oh you're exactly right @marco-m-alves, apologies... my bad! I completely forget about it.

The library is using the cloning algorithm internally when calling `postMessage` on the function passed to it. And per the [structured cloning algorithm ](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) page on MDN:

> Function objects cannot be duplicated by the structured clone algorithm; attempting to throws, a DATA_CLONE_ERR exception.

Which is the exception we see in the sandbox. So yeah, the `localDependencies` feature is a must now...

Let me thinker with this a bit, we will probably need to inline the function declarations on worker creation to have them available inside the function returned by `useWorker`. I'll try to open a PR in a couple of days with an implementation and let's see how we go from there :) 

Thanks for pointing it out!

**Comment by marco-m-alves** [comment]
Thank you for your response. I’m really looking forward to use ˋuseWorkerˋ with this new feature.
