### ISSUE TITLE
Uncaught ReferenceError: _toConsumableArray2 is not defined/

### ISSUE THREAD

**Issue by buitrbao222** [alewin/useWorker#76]
**[Required] Describe the bug**
Bug happens when using spread syntax in the function passed to useWorker.

**[Optional] To Reproduce**
1. Write a function that uses spread syntax
2. Pass that function to useWorker to create a worker
3. Run worker

**[Required] Expected behavior**
The worker to run normally without errors.

**[Optional] Screenshots**

**[Optional] Device (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 84.0.4147.125 (Official Build) (64-bit)

**[Optional] context**
Here's the Codesandbox:
https://codesandbox.io/s/testing-useworker-9rw9j

**Comment by AhmedSayed77** [comment]
check if the solution mentioned in #87 fixes your issue

**Comment by ashish-r** [comment]
Mentioned here: https://github.com/alewin/useWorker/issues/87#issuecomment-699662483
