### ISSUE TITLE
Attempted import error: 'useWorker' is not exported from '@koale/useworker'.

### ISSUE THREAD

**Issue by konraddzbik** [alewin/useWorker#86]
There is a problem when we did try to use useWorker inside our react + TypeScript + webpack. 
Does anyone have a similar problem? Maybe some additional configuration is required, but I cant figure o
ut.

```
Attempted import error: 'useWorker' is not exported from '@koale/useworker'.
```

**Comment by gonzachr** [comment]
Hi @KonradCshark, can you share a bit more about your project setup? Normally, it should just work, here's a codesandbox example:

https://codesandbox.io/s/funny-feather-x930r

**Comment by KonradCshark** [comment]
Sure, but I'm really new in bug/error reporting, what should I share to complete the issue description? 
package.json or tsconfig? Maybe i did something wrong inside the project configuration?

I did try to use worker-loader and everything works fine- but not the way that is easy to read.

**Comment by gonzachr** [comment]
Np! both will be useful, as it will be useful to see which version of `useWorker` you have installed. It may also be something related to where TS is looking for type definitions

**Comment by mudassir-copperpod** [comment]
any update on the fix? facing the same issue with typescript in react.

**Comment by naorpeled** [comment]
Hey @konraddzbik,
I'll be closing this issue as it seems to be resolved in the latest versions.

If you want me to re-open this issue or need any assistance, feel free to ping me.
