### ISSUE TITLE
Add another example to solve 'variable not defined' error caused by transpiling

### ISSUE THREAD

**Issue by AhmedSayed77** [alewin/useWorker#87]
**Is your feature request related to a problem? Please describe.**
I had a pure function that has no external dependencies that worked well in development, but throws a 'l is not defined' error in production. After some debugging that transpiling the code was the cause of this error, as  it inlined some dependency inside the body of my function. This was the function:
```ts
function getHistory(
  readings: Reading[],
): History {
  const countPerTime = readings.reduce((accumulator, {time, value}) => {
    if (!accumulator[time]) {
      accumulator[time] = 0;
    }

    accumulator[time] += Number(value);

    return accumulator;
  }, {} as {[time: string]: number});

  return Object.entries(countPerTime).map(([time, count]) => ({
    time: new Date(time).valueOf(),
    count,
  }));
}
```

**Describe the solution you'd like**
The solution was to replace my function declaration with this:
```ts
const getHistory = new Function(
  'readings',
  `
const countPerTime = readings.reduce((accumulator, {time, value}) => {
  if (!accumulator[time]) {
    accumulator[time] = 0;
  }

  accumulator[time] += Number(value);

  return accumulator;
}, {});

return Object.entries(countPerTime).map(([time, count]) => ({
  time: new Date(time).valueOf(),
  count,
}));
`,
) as (readings: Reading[]) => History;
```
Which prevented the transpiler from altering my code, and it worked. Please add it to your documentation, as it may help other fellow strugglers.

**Comment by gonzachr** [comment]
Hi @AhmedSayed77, thanks for sharing this. 

Would you mind sharing a bit more about your project setup? If you are using Babel or just Typescript and which options do you have enabled

**Comment by AhmedSayed77** [comment]
I use create react app v3.4.3, so I have no control over the build setup. That's the reason this was the only solution available

**Comment by gonzachr** [comment]
Oh I see, we will add this as a caveat since some of the issues we're getting are of this nature. 

To give a little insight, the approach of this library is moving the entire function to the worker side, so when if the function gets transpiled, variable definitions used by the transpiling tool get out of scope and thus undefined causing reference errors.

I'm not sure if there's something we can do on the code side to mitigate this, but at the moment updating the README is a nice option.

Thanks!

**Comment by gonzachr** [comment]
[Known issues](https://github.com/alewin/useWorker#known-issues) added to README.
