### ISSUE TITLE
Uncaught ReferenceError: p is not defined

### ISSUE THREAD

**Issue by lxmw001** [alewin/useWorker#89]
**[Required] Describe the bug**
The dependency is working as expected when testing locally but when I test the application for prod using `yarn build` I got this error:
`Uncaught ReferenceError: p is not defined`

**[Optional] To Reproduce**
1. Run 'yarn build'
2. Run 'serve -s build'
4. Execute the web worker
5. See the error in console.

**[Required] Expected behavior**
Run web worker without problems in prod

**Comment by zant** [comment]
Hi! Would you mind to give us more information about your code and how you're passing it to the hook? Thanks!
