### ISSUE TITLE
useWorker for Sockets

### ISSUE THREAD

**Issue by umernawaz0301** [alewin/useWorker#94]
Can I use useWorker for web sockets? does this library support web sockets?

**Comment by zant** [comment]
Hi! @umernawaz0301 I would think so, as WebSockets in the client are mostly callback based, I will be surprised if there's an issue with that. Do you have any specific use case in mind?

**Comment by ricardona** [comment]
@umernawaz0301  If your want to reduce the server load, the best option is to use SharedWorkers

https://dev.to/ayushgp/scaling-websocket-connections-using-shared-workers-14mj
